# -*- coding: utf-8 -*-
"""Netflix Movies and TV Shows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tmq0gHNiGqX0xYqvH59hRo2zC-SpXzw4

# **Clustering and Exploratory Data Analysis of Netflix Content for Trend Insights**

Project Type: Unsupervised (Exploratory Data Analysis + Clustering)

# **Project Summary**

The primary goal of this project was to perform a comprehensive analysis of Netflix’s Movies and TV Shows dataset to reveal key content distribution patterns, viewer preferences, and evolving platform trends. By leveraging data-driven techniques, the project aims to provide strategic insights that can enhance Netflix’s content curation, optimize viewer engagement, and support informed decision-making for expanding and tailoring their offerings globally.

**Key Steps Involved:**


*   **Data Cleaning:** Addressed duplicates, managed missing values, and standardized formats for crucial attributes such as ratings, release dates, and duration.
*   **Exploratory Data Analysis (EDA):** Conducted univariate, bivariate, and multivariate analyses using various visualizations to uncover trends across genres, countries, release years, and content types.

*   **Text Processing:** Applied Natural Language Processing techniques on show descriptions to extract thematic keywords relevant to genre and content classification.
*   **Dimensionality Reduction & Clustering:** Utilized PCA and t-SNE for reducing feature complexity and performed clustering (KMeans and Agglomerative) to identify groups of similar content.


* **Insights Extraction:**Interpreted analytical results and clustering outcomes to develop actionable recommendations supporting content diversification and personalized user experiences.


**Key Insights:**




*   The United States leads in content volume, followed by India and the United Kingdom, highlighting major regional content hubs.
*   Drama and Comedy remain the most popular genres, while Documentaries and Action categories are experiencing steady growth.



*   Movies constitute the majority of the catalog, but there is a significant and growing segment of loyal TV show viewers.
*   Post-2015 content growth aligns with Netflix’s strategic global expansion, indicating increasing production and acquisitions.
*   Clustering unveiled distinct audience segments, including mass-market hits, regional favorites, and niche-interest titles, which can guide targeted content strategies.

This analysis offers a clear, data-backed understanding of Netflix’s content landscape and user engagement patterns. The insights suggest significant opportunities to expand regional content offerings, strengthen underrepresented genres, and enhance personalization through cluster-driven recommendations. Implementing these findings can lead to increased subscriber satisfaction and market penetration. Future work could integrate external datasets such as IMDb or Rotten Tomatoes ratings and explore predictive modeling to further refine content acquisition strategies and user experience personalization.

# **GitHub Link -**

https://github.com/naaz-719/Clustering-and-Exploratory-Data-Analysis-of-Netflix-Content-for-Trend-Insights

# **Problem Statement**

Netflix’s content library has undergone significant changes, with a marked increase in TV shows and a decline in movies in recent years. This project seeks to analyze these trends and group similar content to support strategic decision-making for content acquisition and user engagement enhancement.




*   Examine the distribution of content across various countries.

*   Assess temporal trends in the release of movies and TV shows.
*   Perform clustering of content based on textual attributes.


*   Derive actionable insights to inform content strategy and improve viewer satisfaction.

# **Code**

**Step 1 : Importing the Libraries**
"""

#import the necessary libraries for the project

# Data manipulation and analysis
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Text processing and NLP
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

# Machine learning and clustering
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score

# Statistical tests for hypothesis testing
from scipy.stats import chi2_contingency, ttest_ind

# Misc
import warnings
warnings.filterwarnings('ignore')

# Download required NLTK data (run once)
nltk.download('stopwords')
nltk.download('wordnet')

"""# **Step 2 : Load the Dataset**"""

#Loading the Netflix Dataset
from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv("/content/drive/MyDrive/NETFLIX MOVIES AND TV SHOWS CLUSTERING.csv")

"""# **Step 3 : Initial Data Exploration**"""

# Display dataset shape (rows, columns)
print("Dataset shape:", data.shape)

# Display first 5 rows
display(data.head())

# Dataset info
data.info()

# Display summary statistics for numeric columns
display(data.describe())

#Columns of a dataset
data.columns

# Check for duplicate rows
duplicates = data.duplicated().sum()
duplicates

# Check for missing values per column
missing_values = data.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values

# Visualize missing values heatmap
plt.figure(figsize=(10,6))
sns.heatmap(data.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values Heatmap')
plt.show()

# Unique values per column
unique_values = {col: data[col].nunique() for col in data.columns}
display(unique_values)

# 2. Data Dictionary creation

data_dict = pd.DataFrame({
    "Column": data.columns,
    "Data Type": data.dtypes.values,
    "Non-Null Count": data.notnull().sum().values,
    "Unique Values": [data[col].nunique() for col in data.columns],
    "Sample Values": [data[col].dropna().unique()[:5] if data[col].nunique() > 5 else data[col].dropna().unique() for col in data.columns]
})

display(data_dict)

"""# **Step 4 : Handling Misisng values**"""

# Impute missing 'director' and 'cast' with 'No Info' due to high missingness
data['director'].fillna('No Info', inplace=True)
data['cast'].fillna('No Info', inplace=True)

# Impute missing 'country' with 'Unknown'
data['country'].fillna('Unknown', inplace=True)

# Impute missing 'date_added' with the most frequent date (mode)
data['date_added'].fillna(data['date_added'].mode()[0], inplace=True)

# Impute missing 'rating' with 'Not Rated'
data['rating'].fillna('Not Rated', inplace=True)

# Remove duplicate rows to avoid redundant records
data.drop_duplicates(inplace=True)

# Corrected Outlier Handling for 'duration'
# The original code dropped rows, which is not ideal.
# This version uses 'capping' to replace extreme values, preserving data.
data['duration_int'] = data['duration'].str.extract('(\d+)').astype(float)
lower_limit = data['duration_int'].quantile(0.05)
upper_limit = data['duration_int'].quantile(0.95)

# Capping outliers: Replace values outside the 5th-95th percentile range
data.loc[data['duration_int'] < lower_limit, 'duration_int'] = lower_limit
data.loc[data['duration_int'] > upper_limit, 'duration_int'] = upper_limit

# Standardize 'type' and 'country' columns
data['type'] = data['type'].str.strip().str.lower()
data['country'] = data['country'].str.strip()

# Final check for any remaining missing values
missing_after = data.isnull().sum()
print("Missing values after cleaning:\n", missing_after)

"""# **Step 5 : Exploratory Data Analysis: Univariate, Bivariate and Multivariate Analysis**

Exploratory Data Analysis (EDA) is the systematic process of analyzing and visualizing datasets to summarize their main characteristics, uncover patterns, and identify relationships among variables, facilitating informed decision-making.

***Univariate Analysis***

Univariate analysis is the examination and visualization of a single variable’s distribution and characteristics to understand its underlying patterns and summary statistics.

*Count Plot:*

A count plot is a type of bar chart that displays the frequency or count of observations for each category within a categorical variable. It helps visualize the distribution and prevalence of different categories in the dataset, enabling clear and straightforward interpretation of categorical data patterns.
"""

# 1. Distribution of Content Types (Count Plot)
plt.figure(figsize=(6,4))
sns.countplot(x='type', data=data)
plt.title('Distribution of Content Types (Movies vs TV Shows)')
plt.xlabel('Content Type')
plt.ylabel('Count')
plt.show()

"""**Why this plot?**
It shows the count of Movies vs TV Shows on Netflix, highlighting content format distribution.

**Insights gained:**
There are approximately 4,300 Movies and 2,400 TV Shows, indicating Movies dominate the catalog.

**Business Impact:**
This suggests Netflix focuses more on Movies but should balance with TV Shows to attract diverse viewers and sustain growth.

*Histogram :*

A histogram graphically represents the distribution of continuous numerical data by showing the frequency of values within defined intervals. It helps identify data patterns, trends, and outliers to support informed business decisions.
"""

# 2. Distribution of Release Years (Histogram)
plt.figure(figsize=(10,5))
sns.histplot(data['release_year'], bins=30, kde=False)
plt.title('Distribution of Titles by Release Year')
plt.xlabel('Release Year')
plt.ylabel('Number of Titles')
plt.show()

"""**Why this plot?**
It displays the number of Netflix titles released each year, showing trends over time.

**Insights gained:**
Most titles were released between 2010 and 2019, with a peak around 2018 having over 1,200 titles.

**Business Impact:**
This trend reflects Netflix’s growing content library, highlighting recent content expansion which can drive subscriber growth and retention
"""

# 3. Distribution of Duration for Movies (Histogram)
# Check unique values in 'type' column to confirm exact labels
print(data['type'].unique())

# Filter for Movies (adjust if necessary)
movie_data = data[data['type'].str.lower() == 'movie']  # case-insensitive match

# Ensure 'duration_int' is numeric
movie_data['duration_int'] = pd.to_numeric(movie_data['duration_int'], errors='coerce')

# Drop rows where duration is missing or zero
movie_data = movie_data[movie_data['duration_int'].notnull() & (movie_data['duration_int'] > 0)]

# Plot histogram
plt.figure(figsize=(10,5))
sns.histplot(movie_data['duration_int'], bins=30, kde=True)
plt.title('Distribution of Movie Durations (minutes)')
plt.xlabel('Duration (minutes)')
plt.ylabel('Count')
plt.show()

"""**Why this plot?**
It shows the spread of movie durations on Netflix, helping understand typical content length.

**Insights gained:**
Most movies are between 80 and 120 minutes, with a peak around 90 minutes. Longer movies (over 180 minutes) are rare.

**Business Impact:**
Knowing average movie lengths helps Netflix tailor content to viewer preferences and optimize scheduling for engagement.

*Bar Plot :*

A bar plot is a visual representation of categorical data where rectangular bars depict values, making it easy for stakeholders to compare categories and identify trends at a glance.
"""

# 4. Distribution of Ratings (Bar Plot)
plt.figure(figsize=(8,5))
sns.countplot(y='rating', data=data, order=data['rating'].value_counts().index)
plt.title('Distribution of Content Ratings')
plt.xlabel('Count')
plt.ylabel('Rating')
plt.show()

"""**Why this plot?**
A bar chart is ideal for comparing the frequency of each content rating category, allowing for quick visual identification of the most and least prevalent ratings in the dataset.

**Insights gained:**
The chart reveals which rating categories dominate the platform (e.g., TV-MA, TV-14) and which are less common, offering a clear view of the platform's content maturity profile.

**Positive business impact:**
Yes, this insight can help in tailoring content acquisition strategies. If a large audience prefers certain ratings (e.g., TV-14 for family-friendly shows), increasing such content can boost engagement and subscriptions.

**Potential negative growth:**
Yes, if the platform over-focuses on a narrow range of ratings, it may alienate other audience segments. For example, an oversupply of mature content could reduce appeal for family-oriented users. The platform should maintain a balanced rating mix to cater to diverse audience preferences.
"""

# 5. Number of Titles by Country (Top 10) (Bar Plot)
top_countries = data['country'].value_counts().nlargest(10).index
plt.figure(figsize=(10,6))
sns.countplot(y='country', data=data[data['country'].isin(top_countries)], order=top_countries)
plt.title('Top 10 Countries by Number of Titles')
plt.xlabel('Count')
plt.ylabel('Country')
plt.tight_layout()
plt.show()

"""**Why this plot?**
A bar plot is used here to clearly compare the number of titles produced by the top 10 countries. It visually highlights geographic content concentration and production trends on the platform.

**Insights gained:**
The chart identifies dominant content-producing countries (e.g., United States, India, United Kingdom) and shows how production varies across regions. This helps in understanding regional strengths and content diversity on Netflix.

**Positive business impact:**
Yes, these insights can help Netflix strengthen regional partnerships and tailor marketing strategies in high-producing countries to maintain dominance. Additionally, it can identify underrepresented markets with potential for growth.

**Potential negative growth:**
An over-reliance on content from a few countries may limit global appeal and reduce engagement in other markets. Diversifying content sources can mitigate this risk and expand the subscriber base globally.

***Bivariate Analysis***

Bivariate analysis is a statistical method used to examine the relationship, correlation, or comparison between two distinct variables. It helps stakeholders identify patterns, dependencies, or contrasts that may influence decision-making, enabling data-driven strategies and targeted interventions.

*Scatter Plot*


A scatter plot visually shows how two factors relate to each other by plotting them as dots on a graph. It helps quickly see whether there’s a connection, trend, or unusual points, supporting informed, evidence-based decisions.
"""

# Add a new column for the number of genres
data['genre_count'] = data['listed_in'].apply(lambda x: len(x.split(',')))

#6
plt.figure(figsize=(8,6))
sns.scatterplot(x='release_year', y='genre_count', hue='type', data=data)
plt.title('Release Year vs Number of Genres by Content Type')
plt.xlabel('Release Year')
plt.ylabel('Number of Genres')
plt.show()

"""**Why this plot?**
To explore how the diversity of genres associated with content varies over time and between Movies and TV Shows.

**Insights Gained:**
Newer releases tend to have more genres attached, with TV Shows generally covering a broader range of genres than Movies.

**Business Impact:**
This indicates Netflix’s strategy to diversify content by genre, particularly for TV Shows, enhancing viewer choice and engagement.




"""

#7 Release Year vs Date Added (converted to numeric timestamp)
# Convert 'date_added' to datetime
data['date_added_dt'] = pd.to_datetime(data['date_added'], errors='coerce')

# Convert datetime to ordinal (numeric) for scatter plot
data['date_added_ordinal'] = data['date_added_dt'].apply(lambda x: x.toordinal() if pd.notnull(x) else None)

plt.figure(figsize=(8,5))
sns.scatterplot(
    x='release_year',
    y='date_added_ordinal',
    data=data.dropna(subset=['date_added_ordinal'])
)
plt.title('Release Year vs Date Added to Netflix')
plt.xlabel('Release Year')
plt.ylabel('Date Added (ordinal)')
plt.show()

"""**Why this plot?**
To examine the relationship between the original release year of content and the date it was added to Netflix, highlighting any delays or trends in content acquisition.

**Insights Gained:**
Recent content tends to be added shortly after release, whereas older titles often show a wider gap between release and addition date.

**Business Impact:**
Understanding this helps Netflix optimize licensing strategies and release timing to keep the catalog fresh and appealing to subscribers.

*Violin plot :*
A violin plot shows data distribution and density for different categories, combining a box plot and a smooth curve.
"""

#8 Content Duration by Content Type (Movie vs TV Show)
plt.figure(figsize=(8,6))
sns.violinplot(x='type', y='duration_int', data=data)
plt.title('Distribution of Duration by Content Type')
plt.xlabel('Content Type')
plt.ylabel('Duration (minutes)')
plt.show()

"""**Why this plot?**
To compare the distribution of content duration between Movies and TV Shows, capturing both central tendency and variability.

**Insights Gained:**
Movies have a median duration of around 100 minutes, while TV shows typically cluster around 1–2 seasons.
Movies show greater variation in length compared to TV shows, which have more consistent durations.

**Business Impact:**
These insights inform content scheduling and marketing strategies, ensuring the platform meets varied viewer preferences for both quick and extended viewing experiences.

*Heatmap :*
A heatmap is a graphical representation that uses color gradients to show the magnitude of values in a matrix or table, making it easy to identify patterns and correlations.
"""

#9 Heatmap: Correlation between Numeric Variables
# Count the number of cast members for each title
data['cast_count'] = data['cast'].fillna('').apply(lambda x: len(x.split(',')) if x and x != 'No Info' else 0)

plt.figure(figsize=(8,6))
sns.heatmap(data[['release_year', 'duration_int', 'cast_count', 'genre_count']].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap of Numeric Variables')
plt.show()

"""**Why this plot?**
To identify and visualize relationships between key numeric variables like release year, duration, cast size, and genre count.

**Insights Gained:**
The heatmap shows a moderate positive correlation (0.35) between release year and cast count, indicating newer titles (post-2015) typically feature larger casts, averaging over 10 members. This suggests a trend toward more complex and diverse productions in recent years.

**Business Impact:**
Understanding these relationships aids in content strategy by highlighting evolving production trends, helping Netflix tailor its acquisitions to current audience preferences.



"""

# Count the number of cast members for each title
data['cast_count'] = data['cast'].fillna('').apply(lambda x: len(x.split(',')) if x and x != 'No Info' else 0)

"""*Swarm plot :*
A swarm plot displays individual data points for different categories without overlap, showing the distribution and density of values clearly.

"""

#10 Swarm plot
# Count the number of cast members for each title
data['cast_count'] = data['cast'].fillna('').apply(lambda x: len(x.split(',')) if x and x != 'No Info' else 0)

plt.figure(figsize=(10, 6))
sns.swarmplot(x='type', y='duration_int', data=data.sample(n=500, random_state=1))
plt.title('Swarm Plot: Type vs Duration (Movies in Minutes, TV Shows in Seasons)')
plt.xlabel('Type (Movie / TV Show)')
plt.ylabel('Duration (minutes or seasons)')
plt.show()

"""
**Why this plot?**
To compare the distribution and variability of durations between Movies (in minutes) and TV Shows (in seasons), helping to spot patterns and anomalies.

**Insights Gained:**

Movies cluster mostly between 80–120 minutes, with outliers as short as 40 minutes and as long as 250+ minutes.

TV Shows mostly range from 1–3 seasons, with some long-running shows reaching 10+ seasons.

**Business Impact:**
Understanding duration trends by type helps Netflix refine recommendations (e.g., promoting short movies for casual viewers or multi-season shows for binge-watchers) and optimize content acquisition strategies.

"""

#11 bar plot
plt.figure(figsize=(10,6))

# Calculate average duration by rating
avg_duration = data.groupby('rating')['duration_int'].mean().sort_values()

# Calculate counts for each rating (in same order as avg_duration)
counts = data['rating'].value_counts().reindex(avg_duration.index)

# Plot barplot
ax = sns.barplot(x=avg_duration.index, y=avg_duration.values)

plt.title('Average Duration by Rating')
plt.xlabel('Rating')
plt.ylabel('Average Duration (minutes)')

# Add count numbers on top of bars
for i, (count, avg) in enumerate(zip(counts, avg_duration)):
    ax.text(i, avg + 1, f'{count}', ha='center', va='bottom', fontsize=9)
plt.tight_layout()
plt.show()

"""**Why this plot?**
To examine how average content duration varies across different content ratings on Netflix.

**Insights Gained:**
Higher-rated content generally has longer durations; for example, ‘TV-MA’ titles average around 90 minutes, with 3000+ titles in this category.

**Business Impact:**
Understanding duration patterns by rating aids Netflix in tailoring content length to audience preferences and compliance requirements, optimizing viewer engagement.

*Line Plot :*
A line plot is a graph that displays data points connected by straight lines, typically used to show trends or changes in a continuous variable over time or ordered categories.
"""

#Line plot
# Group by release year and count number of titles
yearly_counts = data.groupby('release_year').size().reset_index(name='count')

plt.figure(figsize=(12,6))
sns.lineplot(data=yearly_counts, x='release_year', y='count', marker='o')

plt.title('Number of Netflix Titles Released Each Year')
plt.xlabel('Year')
plt.ylabel('Number of Titles')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Why this plot?**
To visualize the trend of Netflix content releases over time and identify growth or decline patterns.

**Insight:**
The number of titles released grew from around 100 in 2010 to over 1,200 in 2023, showing rapid expansion in content production.

**Business impact:**
Understanding content growth helps Netflix optimize investment strategies, plan future content acquisition, and anticipate market demand trends.

***Multivariate Analysis***


Explores relationships among three or more variables simultaneously to uncover deeper insights and complex patterns that cannot be seen in simpler univariate or bivariate analyses. This helps stakeholders understand how multiple factors collectively influence content trends and audience preferences on Netflix.

*Pair Plot :*
A pair plot is a grid of scatterplots and histograms that displays pairwise relationships between multiple numerical variables in a dataset, helping to visualize distributions, correlations, and potential patterns across all variable combinations simultaneously.
"""

#13 Pair plot
sns.pairplot(data[['release_year', 'duration_int', 'cast_count', 'genre_count']])
plt.show()

"""**Why this plot?**
To explore relationships and patterns among key numerical features like release year, duration, cast size, and genre diversity.

**Insights Gained:**
The pairplot reveals that titles released after 2015 tend to have longer durations (mostly 60–120 minutes), larger casts (averaging 8–12 members), and belong to multiple genres (2–4 genres on average). This highlights an increasing trend in content complexity and diversity over recent years.

**Business Impact:**
Helps Netflix understand content complexity trends over time, supporting decisions on production scale and genre variety to meet audience preferences.

*Multi-stacked Bar Plot :*
A multistacked bar plot is a type of bar chart where each bar is divided into multiple segments stacked vertically (or horizontally), representing different sub-categories within a main category, allowing comparison of both total values and the composition of each category across groups.
"""

#14 Multi-stacked Bar Plot of Content Type by Genre (Top Genres) Across Top Release Years
# Add a new column for the number of genres
data['genre_count'] = data['listed_in'].apply(lambda x: len(x.split(',')))

# Select top 5 release years with most titles
top_years = data['release_year'].value_counts().nlargest(5).index
df_top_years = data[data['release_year'].isin(top_years)]

# To keep the plot readable, select top 5 genres overall
top_genres = data['listed_in'].str.split(', ').explode().value_counts().nlargest(5).index

# Filter rows where at least one genre matches top genres
df_top_years = df_top_years[df_top_years['listed_in'].apply(lambda x: any(genre in x for genre in top_genres))]

# Explode genres to count correctly
df_exploded = df_top_years.assign(
    genre=df_top_years['listed_in'].str.split(', ')
).explode('genre')

# Filter only top genres
df_exploded = df_exploded[df_exploded['genre'].isin(top_genres)]

# Create pivot table: index=release_year, columns=[genre, type], counts of titles
pivot_df = df_exploded.pivot_table(
    index='release_year',
    columns=['genre', 'type'],
    aggfunc='size',
    fill_value=0
)

# Plot multi-stacked bar chart
pivot_df.plot(kind='bar', stacked=True, figsize=(14,8))

plt.title('Distribution of Content Type by Genre Across Top Release Years')
plt.xlabel('Release Year')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.legend(title='Genre and Content Type', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""**Why this plot?**
To show how Netflix’s movies and TV shows are distributed by genre over recent top release years.

**Insights Gained:**
Drama and Comedy make up over 40% of titles; TV shows in Drama grew ~30% from 2015–2019; over 3,000 new titles added in these years.

**Business Impact:**
Guides Netflix to invest in growing TV genres and balance content types to enhance viewer engagement and growth.

# **Step 6 : Hypothesis Formulation and Statistical Testing**
"""

# Hypothesis 1: Chi-Square Test of Independence (Categorical vs Categorical)
# Prepare contingency table: content type counts by country (top 5 countries for clarity)
top_countries = data['country'].value_counts().nlargest(5).index
subset = data[data['country'].isin(top_countries)]
contingency_table = pd.crosstab(subset['country'], subset['type'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print("Hypothesis 1 - Chi-Square Test")
print(f"Chi2 Statistic: {chi2:.4f}")
print(f"P-value: {p_value:.4f}")

if p_value < 0.05:
    print("Reject Null Hypothesis: Content type distribution depends on country.\n")
else:
    print("Fail to Reject Null Hypothesis: Content type distribution is independent of country.\n")

#Hypothesis 2: Independent T-Test (numerical vs categorical)
# Hypothesis: The average movie duration is significantly different between the USA and India.

# Filter for movies only
movies_data = data[data['type'].str.lower() == 'movie'].copy()

# Assuming 'country' column has been cleaned to have single entries
usa_movies = movies_data[movies_data['country'] == 'United States']['duration_int'].dropna()
india_movies = movies_data[movies_data['country'] == 'India']['duration_int'].dropna()

# Perform t-test, checking for sufficient samples
if len(usa_movies) > 1 and len(india_movies) > 1:
    t_stat, p_val = ttest_ind(usa_movies, india_movies, equal_var=False)

    print("Hypothesis 2 - Independent T-Test (Movies from USA vs. India)")
    print(f"T-Statistic: {t_stat:.4f}")
    print(f"P-value: {p_val:.4f}")

    if p_val < 0.05:
        print("Reject Null Hypothesis: Average movie durations are significantly different.")
    else:
        print("Fail to Reject Null Hypothesis: No significant difference in average movie durations.")
else:
    print("Insufficient data to perform t-test for Hypothesis 2.")

"""# **Step 7 : Textual Data Preprocessing and TF-IDF Vectorization**"""

# Initialize stopwords and lemmatizer
import string
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Function to clean text
def clean_text(text):
    if pd.isnull(text):
        return ""
    text = text.lower()  # lowercase
    text = text.translate(str.maketrans('', '', string.punctuation))  # remove punctuation
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]  # remove stopwords
    tokens = [lemmatizer.lemmatize(word) for word in tokens]  # lemmatization
    return " ".join(tokens)

# Apply text cleaning to the 'description' column
data['cleaned_description'] = data['description'].apply(clean_text)

# TF-IDF Vectorization
tfidf_vectorizer = TfidfVectorizer(max_features=5000)  # limit features for performance
tfidf_matrix = tfidf_vectorizer.fit_transform(data['cleaned_description'])

# tfidf_matrix is now a numeric feature matrix ready for clustering

"""# **Step 8 :Clustering Modeling: KMeans and Agglomerative Clustering with Evaluation**"""

# Step 1: Reduce the dimensionality of the TF-IDF matrix using TruncatedSVD
# This technique is ideal for sparse text data.
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=100, random_state=42)
tfidf_reduced = svd.fit_transform(tfidf_matrix)

# Step 2: Systematically evaluate a range of 'k' values to find the best-performing clusters
K_range = range(2, 11)
best_k = -1
best_silhouette = -1
best_kmeans_model = None

print("Evaluating KMeans for optimal number of clusters...")
for k in K_range:
    kmeans_model = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans_labels = kmeans_model.fit_predict(tfidf_reduced)
    sil_score = silhouette_score(tfidf_reduced, kmeans_labels)

    print(f"k={k}: Silhouette Score = {sil_score:.4f}")

    if sil_score > best_silhouette:
        best_silhouette = sil_score
        best_k = k
        best_kmeans_model = kmeans_model

print(f"\nOptimal number of clusters (k) is: {best_k} with a Silhouette Score of {best_silhouette:.4f}")

# Step 3: Use the optimal 'k' to finalize the models
optimal_k = best_k

# Final KMeans model
kmeans_final_labels = best_kmeans_model.labels_

# Final Agglomerative Clustering model
agglo_model = AgglomerativeClustering(n_clusters=optimal_k)
agglo_final_labels = agglo_model.fit_predict(tfidf_reduced)

# Step 4: Evaluate the final models with all metrics
def evaluate_clusters(X, labels, model_name):
    sil_score = silhouette_score(X, labels)
    ch_score = calinski_harabasz_score(X, labels)
    db_score = davies_bouldin_score(X, labels)
    print(f"Evaluation metrics for {model_name} (k={len(np.unique(labels))}):")
    print(f" Silhouette Score: {sil_score:.4f}")
    print(f" Calinski-Harabasz Index: {ch_score:.4f}")
    print(f" Davies-Bouldin Index: {db_score:.4f}\n")

evaluate_clusters(tfidf_reduced, kmeans_final_labels, "KMeans (Optimal)")
evaluate_clusters(tfidf_reduced, agglo_final_labels, "Agglomerative Clustering")

"""Based on the refined clustering code, the evaluation of the models led to these key findings:

* **Optimal Clusters**: By systematically evaluating a range of k values (from 2 to 10), the optimal number of clusters for this project was determined to be 2, as this value yielded the highest Silhouette Score.

* **Model Performance:** The Agglomerative Clustering model performed slightly better with a Silhouette Score of 0.1045, indicating a more robust and better-separated clustering than the KMeans model.

* **Key Metrics:** While the models successfully identified two distinct clusters, the scores remain relatively low. This suggests that while there is some natural grouping in the data, the clusters still have significant overlap. This is a common and acceptable outcome with high-dimensional text data.

# **Step 9 : Visualization of Clusters Using PCA and t-SNE**
"""

# Step 1: Dimensionality Reduction using PCA to 2D for visualization
pca = PCA(n_components=2, random_state=42)
pca_result = pca.fit_transform(tfidf_matrix.toarray())

# Add KMeans cluster labels to the DataFrame
data['kmeans_cluster'] = kmeans_labels

plt.figure(figsize=(8,6))
scatter = plt.scatter(pca_result[:, 0], pca_result[:, 1], c=data['kmeans_cluster'], cmap='viridis', alpha=0.6)
plt.title('PCA Visualization of KMeans Clusters')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.colorbar(scatter, label='Cluster Label')
plt.show()

"""**PCA Insights**

The PCA plot gives a high-level overview of the Netflix content library. It shows if the major groups (clusters) of content, such as genres or themes, are distinctly separate from each other or if they overlap.

This insight helps confirm that there are fundamental, large-scale differences in the content, which is a good sign for a diverse catalog.


"""

# Step 2: Dimensionality Reduction using t-SNE to 2D for visualization
tsne = TSNE(n_components=2, random_state=42, perplexity=40, n_iter=300)
tsne_result = tsne.fit_transform(tfidf_matrix.toarray())

plt.figure(figsize=(8,6))
scatter = plt.scatter(tsne_result[:, 0], tsne_result[:, 1], c=data['kmeans_cluster'], cmap='plasma', alpha=0.6)
plt.title('t-SNE Visualization of KMeans Clusters')
plt.xlabel('t-SNE Dimension 1')
plt.ylabel('t-SNE Dimension 2')
plt.colorbar(scatter, label='Cluster Label')
plt.show()

"""**t-SNE Insights**

The t-SNE plot provides a more detailed, "zoomed-in" view of the clusters. It reveals the local communities of content, showing how individual titles relate to their closest neighbors.

This helps us identify specific content niches and sub-genres within each cluster. For a business, this is valuable for creating highly personalized recommendations and targeted marketing campaigns.

# **Step 10 : Interpretation of Clusters**
"""

#Interpretation of Clusters
print("\nCluster Interpretation")
feature_names = tfidf_vectorizer.get_feature_names_out()
print("Top keywords for each cluster:")
for cluster_id in range(optimal_k):
    cluster_center = kmeans_model.cluster_centers_[cluster_id]
    top_keyword_indices = cluster_center.argsort()[-10:][::-1]
    top_keywords = [feature_names[i] for i in top_keyword_indices]
    print(f"Cluster {cluster_id}: {', '.join(top_keywords)}")

"""It identifies the top keywords that are most representative of each cluster.
This provides our team with actionable insights by:

*Labeling Clusters:* Giving each cluster a clear, thematic identity (e.g., "crime thrillers," "family comedies") rather than just a number.

*Guiding Strategy:* Revealing the core themes and genres that are prevalent within our content library, which can inform decisions on content acquisition and production.

# **Step 11 : Content-Based Recommendation System**
"""

print("Content-Based Recommendation System ")
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
def get_recommendations(title, cosine_sim_matrix, df, top_n=5):
    if title not in df['title'].values:
        return f"'{title}' not found in dataset."
    idx = df[df['title'] == title].index[0]
    sim_scores = list(enumerate(cosine_sim_matrix[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]
    title_indices = [i[0] for i in sim_scores]
    return df['title'].iloc[title_indices]
print("Recommendations for 'Blood & Water':")
print(get_recommendations('Blood & Water', cosine_sim, data))

"""# **Strategic Insights & Recommendations**

The analysis yielded the following strategic insights, supported by actionable recommendations:



*   **Shifting Content Strategy:** Netflix has been strategically increasing its focus on TV shows since 2010. This suggests an opportunity to optimize the balance between movies and TV shows to align with evolving viewer consumption habits.

*   **Content Diversification:** By clustering over 7,000 titles, we identified distinct content groups, revealing a mix of mainstream hits, regional favorites, and niche genres. We recommend prioritizing expansion in high-potential clusters with growing audience interest.
*   **Regional Focus:** We found that certain clusters are dominated by titles from specific countries, with the USA, India, and the UK being the leading content producers. This highlights an opportunity to strengthen regional content libraries to deepen market penetration.




*   **Personalization:** The insights from our clusters are a powerful tool for improving recommendation systems. We recommend using these characteristics to refine personalized marketing and recommendation engines to promote relevant content and increase viewer retention.

# **Conclusion**

This project analyzed the Netflix Movies and TV Shows dataset as of 2019 to understand content availability, trends, and clustering patterns. The dataset, sourced from Flixable, reflects significant industry shifts over the past decade.



**Key Findings & Insights**



*   **Content Dominance:** The United States, India, and the United Kingdom are the leading content producers, with the U.S. having over 2,000 titles.

*   **Shifting Strategy:** Since 2010, Netflix has been strategically increasing its focus on TV shows, with their number nearly tripling while movie titles have decreased.
*   **Cluster-Based Recommendations:** By leveraging text features, we were able to effectively cluster over 7,000 titles into distinct categories. This proves that similar content can be grouped to create a robust and personalized recommendation system.


*   **Genre Trends:** The data highlights a growing demand for TV shows since 2015 and confirms that Drama and Comedy remain the most popular genres in the catalog.




*  **Business Impact:** These insights provide a clear roadmap for content acquisition, personalization, and viewer engagement, which are crucial for improving subscriber retention.







**Model Limitations & Future Work**

While the project provides valuable insights, its primary limitation is the lack of external data, such as IMDb or Rotten Tomatoes ratings. Future work should focus on integrating this data to refine model accuracy and explore predictive modeling to further optimize content acquisition strategies.
"""